theme: null
plugins: []
markdown: kramdown
exclude:
  - .nojekyll
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
permalink: pretty
defaults:
  -
    scope:
      path: ""
    values:
      layout: null 